In [2]:

pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /opt/miniconda3/lib/python3.13/site-packages (9.7.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Banking Dashboard

Problem Statement: 

Developing a basic understanding of risk analytics in banking and financial services and understanding how data is used to minimize the risk of losing money while lending to customers.

Solution: 

With our python visualisations , it helps the company to make decisons based on the applicant;s profile like if the applicant is likely to repay the loan then approving the loan otherwise not.

Dataset overview: 

This dataset basically contains Information about bank details, various client details which consists of multiple tables which are interlinked with each other through keys like primary key and foreign key.

Various tables are: 

Banking Realtionship, Client-Banking, Gender, Investment Advisor and Period.

We basically do is risk-analysis in banking sector.

We have:

Data --> Load into My SQL database --> Sql creates some tables --> use connectors to connect My Sql with Python --> In python we do ( data Cleaning, data preperation) --> EDA(Exploratory data analysis) (wokring with statistics)

In [3]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Banking@12345",
    database="banking_case"
)

cursor = conn.cursor()
cursor.execute("SELECT * FROM banking_data LIMIT 5")

for row in cursor.fetchall():
    print(row)

('IND81288', 'Raymond Mills', 24, 34324, datetime.date(2019, 5, 6), 'Anthony Torres', 'American', 'Safety Technician IV', 'High', 'Jade', Decimal('75384.77'), Decimal('17677.95'), 1, Decimal('484.54'), Decimal('776242.92'), Decimal('1485828.64'), Decimal('603617.88'), Decimal('607332.46'), Decimal('12249.96'), Decimal('1134475.30'), 1, 2, 1, 1, 1)
('IND65833', 'Julia Spencer', 23, 42205, datetime.date(2001, 12, 10), 'Jonathan Hawkins', 'African', 'Software Consultant', 'High', 'Jade', Decimal('289834.31'), Decimal('17398.92'), 1, Decimal('2256.88'), Decimal('1270615.43'), Decimal('641482.79'), Decimal('229521.37'), Decimal('344635.16'), Decimal('61162.31'), Decimal('2000526.10'), 1, 3, 2, 1, 2)
('IND47499', 'Stephen Murray', 27, 7314, datetime.date(2010, 1, 25), 'Anthony Berry', 'European', 'Help Desk Operator', 'High', 'Gold', Decimal('169935.23'), Decimal('42825.90'), 2, Decimal('4568.74'), Decimal('1052715.84'), Decimal('1033401.59'), Decimal('652674.69'), Decimal('203054.35'), Decimal('79071.78'), Decimal('548137.58'), 1, 3, 3, 2, 3)
('IND72498', 'Virginia Garza', 40, 34594, datetime.date(2019, 3, 28), 'Steve Diaz', 'American', 'Geologist II', 'Mid', 'Silver', Decimal('356808.11'), Decimal('5473.15'), 2, Decimal('4205.00'), Decimal('121195.06'), Decimal('1048157.49'), Decimal('1048157.49'), Decimal('234685.02'), Decimal('57513.65'), Decimal('1148402.29'), 0, 4, 4, 1, 4)
('IND60181', 'Melissa Sanders', 46, 41269, datetime.date(2012, 7, 20), 'Shawn Long', 'American', 'Assistant Professor', 'Mid', 'Platinum', Decimal('130711.68'), Decimal('48077.60'), 1, Decimal('3779.49'), Decimal('1048301.95'), Decimal('487782.53'), Decimal('446644.25'), Decimal('128351.45'), Decimal('30012.14'), Decimal('1674412.12'), 0, 3, 1, 2, 5)

In [4]:
pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/miniconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: pymysql in /opt/miniconda3/lib/python3.13/site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/miniconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
from sqlalchemy import create_engine
import pandas as pd

In [8]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "mysql+pymysql://root:Banking%4012345@localhost/banking_case"
)

In [9]:
df = pd.read_sql("SELECT * FROM banking_data", engine)
df.head()

,client_id,name,age,location_id,joined_bank,banking_contact,nationality,occupation,fee_structure,loyalty_classification,...,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,brid,genderid,iaid
0,IND81288,Raymond Mills,24,34324,2019-05-06,Anthony Torres,American,Safety Technician IV,High,Jade,...,1485828.64,603617.88,607332.46,12249.96,1134475.30,1,2,1,1,1
1,IND65833,Julia Spencer,23,42205,2001-12-10,Jonathan Hawkins,African,Software Consultant,High,Jade,...,641482.79,229521.37,344635.16,61162.31,2000526.10,1,3,2,1,2
2,IND47499,Stephen Murray,27,7314,2010-01-25,Anthony Berry,European,Help Desk Operator,High,Gold,...,1033401.59,652674.69,203054.35,79071.78,548137.58,1,3,3,2,3
3,IND72498,Virginia Garza,40,34594,2019-03-28,Steve Diaz,American,Geologist II,Mid,Silver,...,1048157.49,1048157.49,234685.02,57513.65,1148402.29,0,4,4,1,4
4,IND60181,Melissa Sanders,46,41269,2012-07-20,Shawn Long,American,Assistant Professor,Mid,Platinum,...,487782.53,446644.25,128351.45,30012.14,1674412.12,0,3,1,2,5

In [11]:
df.describe()

,age,location_id,estimated_income,superannuation_savings,amount_of_credit_cards,credit_card_balance,bank_loans,bank_deposits,checking_accounts,saving_accounts,foreign_currency_account,business_lending,properties_owned,risk_weighting,brid,genderid,iaid
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3.000000e+03,3.000000e+03,3.000000e+03,3.000000e+03,3000.000000,3.000000e+03,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,51.039667,21563.323000,171305.034263,25531.599673,1.463667,3176.206943,5.913862e+05,6.715602e+05,3.210929e+05,2.329084e+05,29883.529993,8.667598e+05,1.518667,2.249333,2.559333,1.504000,10.425333
std,19.854760,12462.273017,111935.808209,16259.950770,0.676387,2497.094709,4.575570e+05,6.457169e+05,2.820796e+05,2.300078e+05,23109.924010,6.412303e+05,1.102145,1.131191,1.007713,0.500067,5.988242
min,17.000000,12.000000,15919.480000,1482.030000,1.000000,1.170000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,45.000000,0.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000
25%,34.000000,10803.500000,82906.595000,12513.775000,1.000000,1236.630000,2.396281e+05,2.044004e+05,1.199475e+05,7.479440e+04,11916.542500,3.748251e+05,1.000000,1.000000,2.000000,1.000000,5.000000
50%,51.000000,21129.500000,142313.480000,22357.355000,1.000000,2560.805000,4.797934e+05,4.633165e+05,2.428157e+05,1.640866e+05,24341.190000,7.113147e+05,2.000000,2.000000,3.000000,2.000000,10.000000
75%,69.000000,32054.500000,242290.305000,35464.740000,2.000000,4522.632500,8.258130e+05,9.427546e+05,4.348749e+05,3.155750e+05,41966.392500,1.185110e+06,2.000000,3.000000,3.000000,2.000000,15.000000
max,85.000000,43369.000000,522330.260000,75963.900000,3.000000,13991.990000,2.667557e+06,3.890598e+06,1.969923e+06,1.724118e+06,124704.870000,3.825962e+06,3.000000,5.000000,4.000000,2.000000,22.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   client_id                 3000 non-null   object
 1   name                      3000 non-null   object
 2   age                       3000 non-null   int64
 3   location_id               3000 non-null   int64
 4   joined_bank               3000 non-null   object
 5   banking_contact           3000 non-null   object
 6   nationality               3000 non-null   object
 7   occupation                3000 non-null   object
 8   fee_structure             3000 non-null   object
 9   loyalty_classification    3000 non-null   object
 10  estimated_income          3000 non-null   float64
 11  superannuation_savings    3000 non-null   float64
 12  amount_of_credit_cards    3000 non-null   int64
 13  credit_card_balance       3000 non-null   float64
 14  bank_loans                3000 non-null   float64
 15  bank_deposits             3000 non-null   float64
 16  checking_accounts         3000 non-null   float64
 17  saving_accounts           3000 non-null   float64
 18  foreign_currency_account  3000 non-null   float64
 19  business_lending          3000 non-null   float64
 20  properties_owned          3000 non-null   int64
 21  risk_weighting            3000 non-null   int64
 22  brid                      3000 non-null   int64
 23  genderid                  3000 non-null   int64
 24  iaid                      3000 non-null   int64
dtypes: float64(9), int64(8), object(8)
memory usage: 586.1+ KB